CREATE TABLE IF NOT EXISTS user_data (
	user_id SERIAL PRIMARY KEY,
	user_name VARCHAR(50) UNIQUE NOT NULL,
	user_email VARCHAR(50) UNIQUE NOT NULL,
	user_phone VARCHAR(13) UNIQUE NOT NULL,
	user_password VARCHAR(50) NOT NULL,
	user_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	user_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);